services:
  database:
    image: mysql:8
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=echo_app
      - MYSQL_USER=echo_app
      - MYSQL_PASSWORD=echo_app
    ports:
      - "3306:3306"
    volumes:
      - ./volume/mysql:/var/lib/mysql
networks:
  echo-app-network:
    driver: bridge
